jobs:
- job: Strategy
  dependsOn: VS_Latest

  pool:
    vmImage: 'windows-2022'

  strategy:
    matrix:
      Commerce:
        solutionPath: 'D:\\a\\1\\s\\reference\\Commerce\\Commerce.sln'
    #matrix: $[ dependencies.VS_Latest.outputs['generateJson.samplesJson'] ]
  
  variables:
    - name: UseDotNetNativeToolchain
      value: false

  steps:
  - template: build-samples.yml
    parameters:
      solutionPath: ${{ parameters.solutionPath }}